/** Auto-generated by scripts/generate-tempate-types.ts */
export type TTemplateNamespace = "apps/nextjs-app" | "base" | "configs/typescript" | "packages/nextjs-shadcn-ui";
export type TTemplateOption = { label: string; value: TTemplateNamespace };

export const templates: TTemplateOption[] = [
      {
        "label": "Nextjs App",
        "value": "apps/nextjs-app"
      },
      {
        "label": "Base",
        "value": "base"
      },
      {
        "label": "Typescript Config",
        "value": "configs/typescript"
      },
      {
        "label": "Nextjs Shadcn UI",
        "value": "packages/nextjs-shadcn-ui"
      }
    ];
